name: Deploy to GitHub Pages # å·¥ä½œæµåç§°

# è§¦å‘æ¡ä»¶ï¼ˆon:ï¼‰,è¿™é‡Œçš„è§¦å‘æ¡ä»¶æ˜¯å½“pushæ—¶å°±æ‰§è¡Œå·¥ä½œæµ
on:
  push:
    branches:
      - main # å½“æ¨é€åˆ° main åˆ†æ”¯æ—¶è§¦å‘,main æˆ– masterï¼Œæ ¹æ®ä½ çš„ä¸»åˆ†æ”¯åæ¥å†™
  workflow_dispatch: # å…è®¸æ‰‹åŠ¨è§¦å‘

permissions: # æƒé™
  contents: write

# ä»»åŠ¡å®šä¹‰ï¼ˆjobs:ï¼‰,ç›¸å½“äºä»»åŠ¡åˆé›†
jobs:
  deploy: # jobsçš„åç§°
    runs-on: ubuntu-latest # è¿è¡Œç¯å¢ƒï¼šLinuxï¼ˆå¯é€‰ windows-latest/macOS-latestï¼‰
    steps: # æ­¥éª¤
      - name: Checkout code # æ­¥éª¤åç§°
        uses: actions/checkout@v5 # å®˜æ–¹åŠ¨ä½œï¼šæ‹‰å–ä»£ç åˆ°è™šæ‹Ÿæœº

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # éƒ¨ç½²åˆ°GitHubä¸Š
      - name: ğŸš€ Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_branch: gh-pages # default: gh-pages è®¾ç½®è¦ç”¨ä½œ GitHub Pages åˆ†æ”¯çš„åˆ†æ”¯åç§°ã€‚é»˜è®¤å€¼ä¸º gh-pagesã€‚
          publish_dir: ./dist
          cname: cc.jiangyahan.com # å¦‚æœæ²¡æœ‰è‡ªå®šä¹‰åŸŸåå»æ‰è¿™ä¸€è¡Œ
